Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -22,4 +22,12 @@ jobs:
     - name: echi
       run: | 
        echo $AWS_REGION
+    - name: script testing
+      run: |
+          case 4.4 in
+          4.4) echo"Google Nexus 5" ;;
+          6) echo "Google Nexus 6" ;;
+          8) echo "Google Pixel 2" ;;
+          11) echo "Google Pixel 4" ;;
+          *) echo "Invalid option!" && exit 1 ;;
 
