Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,8 +15,23 @@ jobs:
       with:
           persist-credentials: false
           fetch-depth: 0
-          
+    - name: add secret
+      id: ami
+      run: echo "AWS_REGION=${GITHUB_REF##*/}" >> $GITHUB_ENV
+      
     - name: Export current branch
       run: |
         echo "CURRENT_BRANCH=${ GITHUB_REF##*/ }" >> $GITHUB_ENV
+        
+    - name: script testing
+      run: |
+          case $CURRENT_BRANCH in
+          release) echo "AWS_REGION=ap-northeast-1" >> $GITHUB_ENV ;;
+          release-eu) echo AWS_REGION=eu-central-1 >> $GITHUB_ENV ;;
+          release-us) echo AWS_REGION=us-west-2 >> $GITHUB_ENV ;;
+          *) echo "Invalid branch name!" && exit 1 ;;
+          esac
+    - name: echi
+      run: | 
+       echo $AWS_REGION
 
